### ISSUE TITLE
3D Assets + Textures

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#11]
This list can change
assign some other people if you want to check the assets you find
Find 3D assets:
- [ ] Temple
  - [ ] Object
    - [ ] Rocks (5 to 6 types of)
    - [ ] Steps
    - [ ] Doors (arched ?)
    - [ ] Pillars (normal and, if we can, broken)
    - [ ] Ruins (Broken Ceil)
    - [ ] Chairs/Desk
    - [ ] Outer Temple
    - [ ] Magnetic platform
  - [ ] Texture
    - [ ] Cobblestone (Ground, Wall, Ceiling)
    - [ ] Moss
    - [ ] abyss
  - [ ] Other/Particle
    - [ ] Raylight
    - [ ] Volumetric light
- [ ] Forest / Plain
  - [ ] Object
    - [ ] Flowers
    - [ ] Grass
    - [ ] Ferns
    - [ ] Big diamants
    - [ ] Trees (3 to 4 types of)
    - [ ] Dark picks
- [ ] Mountain
- [ ] Lake
  - [ ] Object
    - [ ] Bridge
    - [ ] Lake border
- [ ] Canyon
- [ ] Other
  - [ ] Object
    - [ ] Rocks (4 other types)
    - [ ] Pedestal to save
    - [ ] Rail
  - [ ] Other/Particle
    - [ ] Mist

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
