### ISSUE TITLE
Lore item design/texture

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#12]
Make some texture for lore item
Design UI to show lore item

- [X] Lore items images
- [x] Lore items UI

**Comment by yoanlcq** [comment]
@CoralieGold all items are checked. Does it mean it is finished ? If so, would you mind showing a screenshot ?
  
EDIT: And if so, let's close this issue too.

**Comment by CoralieGold** [comment]
Lore items are in this folder until november:
https://drive.google.com/drive/folders/0B3Ao38qy1EK-dUdzTzBabUJONU0?usp=sharing
They can be re-edited during after.
