### ISSUE TITLE
Level design

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#13]
Make all levels and design the final map

**Comment by firegreen** [comment]
Levels ideas
https://drive.google.com/open?id=1dRQo7cXMPrAiGB4jjQSeKcOHyP40iVJz

**Comment by firegreen** [comment]
Need to improve ideas according to the last meeting:
https://drive.google.com/open?id=1wADGsD34NVq0dYgDp0aVa-O-qwa86g1HAgw2XB95kmE

**Comment by yoanlcq** [comment]
Urgent because this is a prerequisite of modeling parts of the world, which in turn will be placed in a large, streaming world. Like with modeling, we need to get this done ASAP and move on.

**Comment by firegreen** [comment]
The next milestone is to describe each zone of the map, it will be done for monday 8th but it will be rediscussed after

**Comment by firegreen** [comment]
lol

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
