### ISSUE TITLE
Rail

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#17]
Tracks following

**Comment by yoanlcq** [comment]
I'd like to point out that scripts from the `SplineController` package should end up in `Assets/Scripts/3rdParty/SplineController`.  
We should need only the scripts, i.e **NOT** other folders (e.g `Tests`, `Examples` or whatever).

**Comment by firegreen** [comment]
Almost done, missing the snap transition

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
