### ISSUE TITLE
Enemy Actions (no IA)

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#19]
Enemy actions:
- [ ] Moving
- [ ] idle state

Weak enemy:
- [ ] simple attack

Enemy thrower:
- [x] throw cristaux stones

Heavy enemy:
- [ ] earth quake 

- [ ] Manage health

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
