### ISSUE TITLE
Enemy IA

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#20]
Implement FSM
Detect hero

- [ ] Move the character/the enemies by giving a speed
- [ ] Enemies actions

**Comment by yoanlcq** [comment]
"Detect hero" requires [#21](https://github.com/imac2018-3d/StoneEdge/issues/21).

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
