### ISSUE TITLE
Prototype: World Queries / Detection / Path Finding

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#21]
I let you make the brief ^^

**Comment by yoanlcq** [comment]
Hopefully this part isn't too hard - From here, it will be a matter of implementing the relevant parts of our architecture: like `Ground`, `Hero` and `Enemy` components.  
This should include a test scene with test scripts that show how e.g Raycasts can know what kind of object they're pointing to.

Also I'll take care to download the relevant version of `NavMeshComponents` and include it in the project properly.

**Comment by yoanlcq** [comment]
The source repository is [https://github.com/Unity-Technologies/NavMeshComponents/tree/2017.1](https://github.com/Unity-Technologies/NavMeshComponents/tree/2017.1).

The documentation can be found here : [https://github.com/Unity-Technologies/NavMeshComponents/tree/2017.1/Documentation](https://github.com/Unity-Technologies/NavMeshComponents/tree/2017.1/Documentation).  
Yes, just click on the `.md` files.

**Comment by yoanlcq** [comment]
Working on this in the `wqueries` branch.

Quick TODO-list for this:
- [x] Hero
- [x] Enemy
- [x] Ground
- [x] Checkpoint
- [x] PowerUp
- [x] LoreItemPickup

What remains to do is change `CurrentGaveSaveData` and ensure uniqueness of IDs for Checkpoints, PowerUps and LoreItemPickups.  
Also PowerUps shouldn't be an ID ??????

**Comment by yoanlcq** [comment]
This is essentially done; The test scene won't work until the Hero Component is properly implemented, but otherwise everything's in place and has no reason to fail.
