### ISSUE TITLE
Transition between two game state

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#25]
Fading screen between states
Manage Hero's falling
Warping hero

**Comment by CoralieGold** [comment]
19 february

**Comment by firegreen** [comment]
@Yoan, for now I use a "NonMap" Script in a collider to identify area where we shoudn't go, is it okay for you or should we consider out of map as a ground type ?

**Comment by yoanlcq** [comment]
> for now I use a "NonMap" Script in a collider to identify area where we shoudn't go, is it okay for you or should we consider out of map as a ground type ?

Yeah this is great! I would go for a more descriptive name e.g `UnreachableZone` or `UnreachableArea`.
(@firegreen )

**Comment by firegreen** [comment]
is ok normally, need to adapt to the current master branch

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
