### ISSUE TITLE
Hero Abilities

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#27]
Magnetic punch:
Send a magnetic wave
Eject all object which is within the wave

Jump quake:
High jump
Make a quake when falling

- [x] Move the character/the enemies by giving a speed
- [ ] Make him rotate towards its movement direction
- [x] Basic jump with various heights
- [ ] Lock/Unlock abilities
- [x] Prevent guardian actions a certain time (e.g supposedly while taking a hit)
- [x] Prevent guardian actions except changing its facing direction (used for some attacks)

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
