### ISSUE TITLE
Ditch LFTP, find a better way

### ISSUE THREAD

**Issue by yoanlcq** [imac2018-3d/StoneEdge#37]
As we're starting serious work today, the current LFTP-based pipeline is very unsatisfactory; reasons include : 

# It sucks on Windows
Really, it's horrible. People won't want to use this daily.

# We can't access it at school
For some reason the FTP traffic is blocked at school. **This is a big problem** because it lowers our productivity by requiring us to go home in order to pull/push latest assets. **But we need to go fast**.

# Outcomes
I see two possible outcomes to this : 

1. Keep the current situation as it is and deal with it (in which case we close this issue);
2. We find a really better way and everybody's happy (but has to install stuff again).

# Candidates
- [SyncThing](https://syncthing.net/) suggested by @datross. Gonna try it quickly this morning.
- ????? Add other alternatives here ????

**Comment by yoanlcq** [comment]
So I've found this and it seems to work really really well : [prasmussen/gdrive](https://github.com/prasmussen/gdrive)
It's a standalone, cross-platform command-line utility that allows syncing with Google Drive folders.

The only requirement is that synchronization must be enabled with this tool before any content is added to the directory at all. But once it's done, it just works. I tried it on Linux and Windows and it looks good.

Still, I would like to make sure it would work for everyone, so I need a few testers : The point is to see if it still works if I share a folder with you.

# Steps
1. [Download the appropriate executable for your OS](https://github.com/prasmussen/gdrive#downloads) and rename it to `gdrive.exe` (or just `gdrive` on Linux and OS X. You might also need to do `chmod +x ./gdrive` then);
2. Open Git BASH (Windows) or a terminal (Linux/OS X);
3. `cd` to the folder where you downloaded `gdrive`;
4. Create a directory named `foo` (`mkdir foo`);
5. Run `./gdrive.exe sync download 1AZmi5qSC5T0LPeG5B4n4jVADXJByhvvm foo`.  
This is expected to give you an URL to copy-paste in your browser, asking you to log in with your Google account, then give you an access key which you have to copy-paste on the terminal.  
If all goes well, it should then sync two text files from the remote folder into `foo`.  
The access key is stored permanently on your computer so you only have to do it once.

I need only one of you guys to try this and prove that it works.  
If it does, we'll ditch the FTP mess!
cc @CoralieGold @firegreen @LanscelThaledric @datross @Hellowizz

**Comment by LancelThaledric** [comment]
It works ! *Big up*

**Comment by yoanlcq** [comment]
Yep. No more testing needed.  
Now I just need to write the new BASH script (easy), then everyone would need to sync once with the folders.

**Comment by yoanlcq** [comment]
Outdated by #38
