### ISSUE TITLE
Completely ditch LFTP: Welcome `gdrive`!

### ISSUE THREAD

**Issue by yoanlcq** [imac2018-3d/StoneEdge#38]
With #37, we found a better way for storing assets than the LFTP mess we are in.

Let's all forget about LFTP. Instead, we'll use [`gdrive`](https://github.com/prasmussen/gdrive), an open-source utility for syncing Google Drive folders.
In order to ease our workflow, all heavy assets folders have been moved into a new one named `Art` (still under `Assets`). [The upstream Drive folder is here](https://drive.google.com/drive/folders/1ByU_jMm3NDlYJfOJXAb3LZZuuYq186Dy).

**This is probably a breaking change for those that have kept local 3D model (e.g @datross). Please just bear with me.**

# Steps
0. As usual, pull the latest changes with `git pull`;
1. [Download the appropriate executable for your OS](https://github.com/prasmussen/gdrive#downloads) and rename it to `gdrive.exe` (or just `gdrive` on Linux and OS X. You might also need to do `chmod +x ./gdrive` then);  
On Mac OS X, if you have `brew`, you can just do `brew install gdrive` and skip the next step.
2. If necessary, set the PATH variable to contain the folder in which the executable is, or move the executable into some system location (e.g `C:\Windows\System32` on Windows or `/usr/bin` on Linux).
3. Open Git BASH (Windows) or a terminal (Linux/OS X);
4. `cd` to this repo's `Assets/` folder;
5. Run `./art.sh pull` or `./art.sh push`.  
The first time you do this, it's expected to give you an URL to copy-paste in your browser, asking you to log in with your Google account, then give you an access key which you have to copy-paste on the terminal.  

This workflow completely replaces the previous one. The idea is the same, you still do `./art.sh pull` and `./art.sh push`.

# People
Please everyone, follow the steps above then check your box when it works for you.
- [x] @yoanlcq
- [x] @LanscelThaledric 
- [x] @CoralieGold 
- [x] @firegreen 
- [x] @Hellowizz 
- [x] @datross 
- [ ] @luanjunqing

**Comment by yoanlcq** [comment]
A few left to go! Please don't do this too late @datross :)

**Comment by datross** [comment]
Finally I did it! I transfered everything from Models/, so it should be ok to delete the folder I think.

*EDIT(yoanlcq): He meant Models/, not Assets/*
