### ISSUE TITLE
Implement the Camera as defined by the Technical Specs

### ISSUE THREAD

**Issue by yoanlcq** [imac2018-3d/StoneEdge#39]
cc @datross. We'll want to copy from your earlier prototype.

Small TODO list for this:

- [ ] Create a `SeCamera` or `CameraController` component which implements the camera as described in the technical specs.  
- [ ] In `InputActions`, add a convenience method for mapping input directions to world-coordinates directions. We're gonna need this badly.

# Quoting the technical specs

Conceptually, our camera is represented by only the following variables (from which the transform is computed) :
- Yaw (angle around vertical axis);
- Pitch (angle around horizontal axis);
- Current distance from pivot point;

We list other items we should add :
- Pivot point, which is a reference to some Transform component;
- Minimum and maximum distances from pivot point; they act as constraints which make the pivot point "drag” the camera.
- Minimum distance from ground;
- The camera should raycast the ground to satisfy this constraint. This is important if the hero is on a steep hill and the player rotates the camera around the vertical axis by 180 degrees.
- A sphere collider, to avoid penetrating obstacles;
- A function which, given the pitch, returns a factor for multiplying the distance from pivot point. This supposedly makes the camera feel a bit less claustrophobic. We can cheaply compute such a factor by using an affine piecewise function.

## Mapping input to camera-relative movement
Let s be the speed factor for the hero, ax and ay be the input axes, and cam be the camera’s transform component;
Then v, the velocity to give to the hero, may be computed by
```csharp
var v = Vector3.zero;
v += s * ax * Vector3.ProjectOnPlane(cam.right, Vector3.up).normalized;
v += s * ay * Vector3.ProjectOnPlane(cam.forward, Vector3.up).normalized;
```

**Comment by yoanlcq** [comment]
Whoops, the correct algorithm is
```csharp
var v = rigidbody.velocity;
v.x = 0f;
v.z = 0f;
v += ax * Vector3.ProjectOnPlane(camera.transform.right, Vector3.up).normalized;
v += ay * Vector3.ProjectOnPlane(camera.transform.forward, Vector3.up).normalized;
rigidbody.velocity = v.normalized * s;
```
To preserve the Y velocity.

**Comment by datross** [comment]
I added the prototype I did in the project. (TestsScenes/follow camera). I'm gonna adapt this more seriously with the components you mentioned.

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
