### ISSUE TITLE
Everyone must read the Technical Specs carefully and entirely 

### ISSUE THREAD

**Issue by yoanlcq** [imac2018-3d/StoneEdge#6]
Title says it all. **Ideally, everyone should do this before resuming work on the project.**

You can find it in our Drive, in the `TechnicalSpecs` folder.

Please, **do not skim through the document, every line counts and must be understood by everyone in the team**.

One you've read the technical specs and have no more questions, please check the box next to your name in the list below (you should be able to. If not, leave a comment and I'll do it).

- [x] @yoanlcq
- [x] @CoralieGold 
- [x] @luanjunqing 
- [x] @datross 
- [x] @firegreen 
- [ ] @Hellowizz 
- [ ] @LanscelThaledric 
- [ ] @seaofhymn 

Feel free to leave comments in this issue if you have questions or remarks.

(Also @CoralieGold, should we treat the document as done and send it to the teacher now ?)

**Comment by datross** [comment]
Done for me.

**Comment by firegreen** [comment]
read

**Comment by yoanlcq** [comment]
@Hellowizz @LanscelThaledric you're practically the only two remaining :)
