### ISSUE TITLE
Everyone must be able to use the Asset Pipeline script `lftp_assets.sh`

### ISSUE THREAD

**Issue by yoanlcq** [imac2018-3d/StoneEdge#7]
This one is important too: otherwise you **won't** be able to add sounds, 3D models etc to the project.

Quick refresher : We **DO NOT** use Git to store audio files, 3D models and images, because **they are too heavy**. Instead, we use an FTP (File Transfer Protocol) server, and I've written an `lftp_assets.sh` BASH script that automagically synchronises all assets with the server in a single line.  
For you to use this, you'll need a BASH shell and the LFTP utility.  
The password is written in our Facebook group. **DO NOT** copy it here or on Gitter.

I had written a guide in our Drive, under `Miscellaneous` -> `LFTP Assets Guide`. If you're feeling lazy, [here's a direct link](https://docs.google.com/document/d/1zQ5ojM8iNpt184iEXKcnNf6SW4yV7GfYXIACtHg_ZVo/edit?usp=sharing).

Once you were able to pull + push assets using this script and have no more questions, please check the box next to your name in the list below (you should be able to. If not, leave a comment and I'll do it).

- [x] @yoanlcq
- [x] @firegreen 
- [ ] @seaofhymn 
- [x] @CoralieGold 
- [x] @Hellowizz 
- [x] @luanjunqing 
- [x] @datross 
- [x] @LanscelThaledric 

**N.B** if you're stuck or don't really know or understand what to do, **do not stay silent** ! **do tell me** so I can help you. This is very important.

**Comment by datross** [comment]
Done for me.


...is it the right way to say it? I cannot find how to check the '@datross' box. Only the author can edit the initial message?

**Comment by yoanlcq** [comment]
@datross I feared this was the case... Quite inconvenient :( I'll check your box and investigate this.

**Comment by Hellowizz** [comment]
J'ai fait ce que tu as dis pour windows (je crois) 
Mais je comprend pas ce que c'est et à quoi ça sert, tu pourrais expliquer un peu plus, histoire que je sache si j'ai bien fait please ?

**Comment by yoanlcq** [comment]
@Hellowizz Normalement y'a tout qui est expliqué dans le guide et la section appropriée du CDCT (au pire Ctrl + F), du coup je t'invite à relire les deux parce que j'ai la flemme de tout réécrire une énième fois ici ^^  
Tu sais que tu as réussi si tu peux ouvrir Git Bash et que, si tu tapes `lftp`, ça fait pas `commande introuvable`. Si t'as besoin d'aide go me MP sur Messenger ^^

**Comment by firegreen** [comment]
I can't enter the password :'(
```
open: GetPass() failed -- assume anonymous login
mirror: Login failed: 530 Login authentication failed
```

**Comment by yoanlcq** [comment]
I assume you're on Windows - all sorts of crazy stuff happens with LFTP on Windows, the situation is very bad; Hélo and Coralie also had problems, each in a specific and hard to solve way.  
This is gonna be tough. Try the following, if it works I'll add it to the guide.

## Windows 

1. Double-click on `bash.exe` from the downloaded LFTP folder;
2. `cd Absolute/Path/To/StoneEdge/Assets`
3. `./lftp_assets.sh login`

Normally, its the `bash.exe` from LFTP that solves everything. let me know if it works for you @firegreen ^^

**Comment by firegreen** [comment]
It works 
Well play 👍

**Comment by LancelThaledric** [comment]
It seems to work for me, but take care ! On windows, my Git configuration fetches files converting new lignes to windows-style (CRLF), making your `lftp_assets.sh` fail to run on lftp bash.
I had to convert new lines to unix-style before run it (I used Notepad++).
I have some warnings but it seems to work.
By the way, I've a new version of your script to add to git ignore list :/

**Comment by yoanlcq** [comment]
> By the way, I've a new version of your script to add to git ignore list :/

@LanscelThaledric Feel free to add the name of your unix-style manual copy to the `.gitignore` in `Assets/` and push this change!  
Also could you tell me which warnings you get ?

**Comment by LancelThaledric** [comment]
`./backup_assets.sh: line 2: $'\r': command not found
./backup_assets.sh: line 3: syntax error near unexpected token `$'do\r''
'/backup_assets.sh: line 3: `for i in `find Textures Models Sounds Music -type f`; do`

Do I have to rename it to not conflict with the original one ?

**Comment by yoanlcq** [comment]
From these errors it appears that there are still some `\r` left. Make sure to remove them all, there must be none left :smiling_imp: 

> Do I have to rename it to not conflict with the original one ?

Unless your Git also converts to Window-style when uploading (which might or might not be the case), please do. I'm fine with anything as long as the upstream one is still Unix-style.

**Comment by LancelThaledric** [comment]
The fact is that on windows, git commit and pushes Unix-style, but pull Windows-style (it's convenient to use, but we have guarantee that no CRLF endings will be pushed on git).
The problem here is that this file is the one that we don't expect to have CRLF endings on windows (lftp seems to be an unix virtual machine). I think push Unix-style endings won't solve the problem, because git will always convert it to windows-style on pulling.
I guess there is a way to fix this locally, I'll search.

**Comment by yoanlcq** [comment]
Note to self: Make life easier for Windows users. The current situation is a mess.  
Here's what I've taken note of:

- Most people's Git fetches Windows-style, but pushes Unix-style;
- The `#!/usr/bin/bash` line makes Cygwin's bash cry.

**Comment by yoanlcq** [comment]
Closing this because everyone appears to be fine!

**Comment by yoanlcq** [comment]
Ok, so today I've tested [my latest commit](https://github.com/imac2018-3d/StoneEdge/commit/9750a6d2500a715bee0e152f84d49518d7d81c21) which hopefully fixed the issues on Windows.  
That is, it forces `\n` line endings instead of `\r\n` (thanks to a `.gitattributes` file), and I've removed the `#!/usr/bin/bash` shebang in relevant scripts.

So, on Window, the process definitely is : 

1. Double-click on `bash.exe` as distributed with LFTP; this opens a terminal window;
2. `cd` to the project's `Assets` directory (in my case, `cd /cygdrive/c/Users/Yoon/StoneEdge/Assets`);
3. Run `./lftp_assets.sh pull`.

Could some of you guys please try it out on Windows with the latest changes ?

- [ ] @CoralieGold 
- [ ] @LanscelThaledric 
- [ ] @Hellowizz 
- [ ] @firegreen (If you're on Windows of course; I'm not sure).

**Comment by yoanlcq** [comment]
Outdated by #38
