### ISSUE TITLE
Enemies Modeling

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#9]
Enemy Modeling:
- [ ] Enemy 1 (the weak one):
  - [ ] Modeling
  - [ ] Rigging
  - [ ] Animation
- [ ] Enemy 2 (the thrower):
  - [ ] Modeling
  - [ ] Rigging
  - [ ] Animation
- [ ] Enemy 3 (the big one):
  - [ ] Modeling
  - [ ] Rigging
  - [ ] Animation

**Comment by yoanlcq** [comment]
Closing because production has ended this afternoon. Thanks everyone!
